drop function associates;
DROP ALL FUNCTION distanceo_ut;
DROP ALL FUNCTION distance_ut;
DROP ALL PROCEDURE gwac_uniquecatalog;
DROP ALL PROCEDURE delete_inactive_unique;
DROP ALL PROCEDURE insert_new_assoc;
DROP ALL PROCEDURE insert_new_uniq;
DROP ALL PROCEDURE update_1_to_1_uniq;
DROP ALL PROCEDURE insert_1_to_1_assoc;
DROP ALL PROCEDURE flag_1_to_n_inactive_tempuniq;
DROP ALL PROCEDURE delete_1_to_n_inactive_assoc;
DROP ALL PROCEDURE insert_1_to_n_replacement_assoc;
DROP ALL PROCEDURE insert_new_1_to_n_assoc;
DROP ALL PROCEDURE flag_1_to_many_inactive_unique;
DROP ALL PROCEDURE insert_1_to_n_unique;
DROP ALL PROCEDURE flag_n_to_m_tempunique;
DROP ALL PROCEDURE insert_tempuniquecatalog;
